version: '3'

tasks:
  run:
    cmds:
      - python tests/file_viewer.py
  install-dev:
    cmds:
      - pip install -r requirements.txt
  install-test:
    cmds:
      - echo "--- install from test repo ---"
      - python -m pip install -U --index-url https://test.pypi.org/simple/ --no-deps TkEasyGUI
      - echo "*** check yoru version ***"
  install-main:
    cmds:
      - echo "--- install from main repo ---"
      - python -m pip install -U TkEasyGUI
  check:
    cmds:
      - ruff check
      - mypy TkEasyGUI/
  lint:
    cmds:
      - ruff check
      - mypy TkEasyGUI/
  test:
    cmds:
      - ruff check
      - echo "*** TODO ***"
  build-docs:
    cmds:
      - echo "Buikding..."
      - python3 update_version.py
      - python makedoc.py
      - python docs/scripts/readme_maker.py
      - echo "ok."
  deploy-build-only:
    cmds:
      - task build-docs
      - echo "Deploying..."
      - echo "-- remove cache ---"
      - rm -f -r dist
      - rm -f -r tkeasygui.egg-info
      - echo "build package"
      - python -m build
  deploy-test:
    cmds:
      - task deploy-build-only
      - echo "--- upload to testpypi ---""
      - python -m twine upload --repository testpypi dist/* --verbose
      - echo "[TRY] task install test"
  deploy-main:
    cmds:
      - task deploy-build-only
      - echo "--- upload to pypi(main) ---"
      - python -m twine upload dist/* --verbose


