version: '3'

tasks:
  install:
    cmds:
      - pip install -r requirements.txt
  check:
    cmds:
      - ruff check
  test:
    cmds:
      - ruff check
      - echo "*** TODO ***"
  build:
    cmds:
      - echo "Buikding..."
      - python3 update_version.py
      - python makedoc.py
      - python docs/scripts/readme_maker.py
      - echo "ok."
  deploy:
    cmds:
      - task build
      - echo "Deploying..."
      - echo "-- remove cache ---"
      - rm -f -r dist
      - rm -f -r tkeasygui.egg-info
      - echo "build package"
      - python -m build
      - python -m twine upload --repository testpypi dist/* --verbose
      - echo "--- install from test repo ---"
      - echo "[TRY] python -m pip install -U --index-url https://test.pypi.org/simple/ --no-deps TkEasyGUI"
      - echo "*** check version ***"
      - echo "--- upload pypi ---"
      - echo "[TRY] python -m twine upload dist/* --verbose"


