blank_issues_enabled: false
contact_links:
  - name: Issues
    url: https://github.com/kujirahand/tkeasygui-python/issues
    about: See the issues page for more information.
  - name: Discord
    url: https://discord.gg/NX8WEQd42S
    about: You can chat with us on Discord. Feel free to join and leave a comment.


